In [31]:
import os
import sqlite3
import pandas as pd
import traceback
import matplotlib.pyplot as plt
import math 

def converter_valor(valor):
    
    
    if type(valor) == str:

        valor = valor.replace('R$', '').strip()
        valor = valor.replace('.', '').replace(',', '.')
        
        if "-" in valor:
            valor = valor.replace("-","").strip()
        
        # Identifica se é milhão (M) ou bilhão (B)
        if 'B' in valor:
            numero = float(valor.replace('B', '').replace(',', '.').strip())
            return numero * 1_000_000_000, 'B'
        elif 'M' in valor:
            numero = float(valor.replace('M', '').replace(',', '.').strip())
            return numero * 1_000_000, 'M'
        elif 'T' in valor:
            numero = float(valor.replace('T', '').replace(',', '.').strip())
            return numero * 1_000_000_000_000, 'T'
        elif "mil" in valor:
            numero = float(valor.replace('mil', '').replace(',', '.').strip())
            return numero * 1_000, 'mil'
        else:
            return valor, ''
    else:
        return 0

In [32]:
diretorio = "C:\\Users\\harri\\Documents\\Programacao\\Python\\ScrappingFinanceiros\\DadosDeMercado\\dividendos"

banco = "db.sqlite3"


resumoEmpresaBp_df = pd.DataFrame()
resumoEmpresaDre3Meses_df = pd.DataFrame()
resumoEmpresaDre12Meses_df = pd.DataFrame()
resumoEmpresaFc3Meses_df = pd.DataFrame()
resumoEmpresaFc12Meses_df = pd.DataFrame()
resumoEmpresaPrecosRelativos_df= pd.DataFrame()


for tickerDir in os.listdir(diretorio):
    
    if os.path.isdir(tickerDir):
        
        try:
            conn = sqlite3.connect(banco)
            cursor = conn.cursor()
            
            cursor.execute("SELECT id_ticker FROM tickers WHERE Ticker = ?", (tickerDir,))
            resultado = cursor.fetchone()
            
            conn.commit()
            conn.close()

            
            for files in os.listdir(diretorio+"\\"+tickerDir):
                
                tabela_df = pd.read_csv(diretorio+"\\"+str(tickerDir)+"\\"+str(files))
                tabela_df["ticker"] = resultado[0]
                tabela_df = tabela_df.drop(tabela_df.columns[[0]], axis=1)

                tabela_df = tabela_df.iloc[::-1].reset_index(drop=True)
                
                
                if "resumoEmpresaBp" in files:
                    
                    tabela_df[['ativo_total_valor', 'ativo_total_unidade']] = tabela_df['ativo_total'].apply(converter_valor).apply(pd.Series)
                    tabela_df[['patrimonio_liq_valor', 'patrimonio_liq_unidade']] = tabela_df['patrimonio_liq'].apply(converter_valor).apply(pd.Series)
                    tabela_df[['vlr_patrimonial_acao_valor', 'vlr_patrimonial_unidade']] = tabela_df['vlr_patrimonial_acao'].apply(converter_valor).apply(pd.Series)
                    tabela_df['ativo_total_valor'] = (tabela_df['ativo_total_valor'])
                    tabela_df['patrimonio_liq_valor'] = (tabela_df['patrimonio_liq_valor'])
                    
                    resumoEmpresaBp_df = pd.concat([resumoEmpresaBp_df,tabela_df])
                
                
                if "resumoEmpresaFc3Meses" in files:

                        tabela_df[['fluxo_caixa_operacional_valor', 'fluxo_caixa_operacional_unidade']] = tabela_df['fluxo_caixa_operacional'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_investimentos_valor', 'fluxo_caixa_investimentos_unidade']] = tabela_df['fluxo_caixa_investimentos'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_financiamentos_valor', 'fluxo_caixa_financiamentos_unidade']] = tabela_df['fluxo_caixa_financiamentos'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_equivalentes_valor', 'fluxo_caixa_equivalentes_unidade']] = tabela_df['fluxo_caixa_equivalentes'].apply(converter_valor).apply(pd.Series)
                        

                        tabela_df['fluxo_caixa_operacional_valor'] = (tabela_df['fluxo_caixa_operacional_valor'])
                        tabela_df['fluxo_caixa_investimentos_valor'] = (tabela_df['fluxo_caixa_investimentos_valor'])
                        tabela_df['fluxo_caixa_financiamentos_valor'] = (tabela_df['fluxo_caixa_financiamentos_valor'])
                        tabela_df['fluxo_caixa_equivalentes_valor'] = (tabela_df['fluxo_caixa_equivalentes_valor'])
                        
                        resumoEmpresaFc3Meses_df = pd.concat([resumoEmpresaFc3Meses_df,tabela_df])
                        
                    
                
                if "resumoEmpresaFc12Meses" in files:

                        
                        tabela_df[['fluxo_caixa_operacional_valor', 'fluxo_caixa_operacional_unidade']] = tabela_df['fluxo_caixa_operacional'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_investimentos_valor', 'fluxo_caixa_investimentos_unidade']] = tabela_df['fluxo_caixa_investimentos'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_financiamentos_valor', 'fluxo_caixa_financiamentos_unidade']] = tabela_df['fluxo_caixa_financiamentos'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['fluxo_caixa_equivalentes_valor', 'fluxo_caixa_equivalentes_unidade']] = tabela_df['fluxo_caixa_equivalentes'].apply(converter_valor).apply(pd.Series)
                        

                        tabela_df['fluxo_caixa_operacional_valor'] = (tabela_df['fluxo_caixa_operacional_valor'])
                        tabela_df['fluxo_caixa_investimentos_valor'] = (tabela_df['fluxo_caixa_investimentos_valor'])
                        tabela_df['fluxo_caixa_financiamentos_valor'] = (tabela_df['fluxo_caixa_financiamentos_valor'])
                        tabela_df['fluxo_caixa_equivalentes_valor'] = (tabela_df['fluxo_caixa_equivalentes_valor'])
                        
                        resumoEmpresaFc12Meses_df = pd.concat([resumoEmpresaFc12Meses_df,tabela_df])
                        
                
                
                if "resumoEmpresaPrecosRelativos" in files:

                        tabela_df[['market_cap_empresa_valor', 'market_cap_empresa_unidade']] = tabela_df['market_cap_empresa'].apply(converter_valor).apply(pd.Series)
                        
                        resumoEmpresaPrecosRelativos_df = pd.concat([resumoEmpresaPrecosRelativos_df,tabela_df])
                

                if "resumoEmpresaDre3Meses" in files:

                        tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['resultado_bruto_valor', 'resultado_bruto_unidade']] = tabela_df['resultado_bruto'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['ebit_valor', 'ebit_unidade']] = tabela_df['ebit'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['depreciacao_valor', 'depreciacao_unidade']] = tabela_df['depreciacao'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['ebitda_valor', 'ebitda_unidade']] = tabela_df['ebitda'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['lucro_liquido_valor', 'lucro_liquido_unidade']] = tabela_df['lucro_liquido'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['lucro_acao_valor', 'lucro_acao_unidade']] = tabela_df['lucro_acao'].apply(converter_valor).apply(pd.Series)

                        tabela_df['receita_liquida_valor'] = (tabela_df['receita_liquida_valor'])
                        tabela_df['resultado_bruto_valor'] = (tabela_df['resultado_bruto_valor'])
                        tabela_df['ebit_valor'] = (tabela_df['ebit_valor'])
                        tabela_df['depreciacao_valor'] = (tabela_df['depreciacao_valor'])
                        tabela_df['lucro_liquido_valor'] = (tabela_df['lucro_liquido_valor'])
                        tabela_df['lucro_acao_valor'] = (tabela_df['lucro_acao_valor'])

                        resumoEmpresaDre3Meses_df = pd.concat([resumoEmpresaDre3Meses_df,tabela_df])
                
                
                if "resumoEmpresaDre12Meses" in files:

                        tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['resultado_bruto_valor', 'resultado_bruto_unidade']] = tabela_df['resultado_bruto'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['ebit_valor', 'ebit_unidade']] = tabela_df['ebit'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['depreciacao_valor', 'depreciacao_unidade']] = tabela_df['depreciacao'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['ebitda_valor', 'ebitda_unidade']] = tabela_df['ebitda'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['lucro_liquido_valor', 'lucro_liquido_unidade']] = tabela_df['lucro_liquido'].apply(converter_valor).apply(pd.Series)
                        tabela_df[['lucro_acao_valor', 'lucro_acao_unidade']] = tabela_df['lucro_acao'].apply(converter_valor).apply(pd.Series)

                        tabela_df['receita_liquida_valor'] = (tabela_df['receita_liquida_valor'])
                        tabela_df['resultado_bruto_valor'] = (tabela_df['resultado_bruto_valor'])
                        tabela_df['ebit_valor'] = (tabela_df['ebit_valor'])
                        tabela_df['depreciacao_valor'] = (tabela_df['depreciacao_valor'])
                        tabela_df['lucro_liquido_valor'] = (tabela_df['lucro_liquido_valor'])
                        tabela_df['lucro_acao_valor'] = (tabela_df['lucro_acao_valor'])

                        resumoEmpresaDre12Meses_df = pd.concat([resumoEmpresaDre12Meses_df,tabela_df])
        
        except Exception as e:
            traceback.print_exc()



path = "resumos"
print("Salvando")
resumoEmpresaBp_df.to_csv(path+"\\resumoEmpresaBp_df.csv")
resumoEmpresaDre3Meses_df.to_csv(path+"\\resumoEmpresaDre3Meses_df.csv")
resumoEmpresaDre12Meses_df.to_csv(path+"\\resumoEmpresaDre12Meses_df.csv")
resumoEmpresaFc3Meses_df.to_csv(path+"\\resumoEmpresaFc3Meses_df.csv")
resumoEmpresaFc12Meses_df.to_csv(path+"\\resumoEmpresaFc12Meses_df.csv")
resumoEmpresaPrecosRelativos_df.to_csv(path+"\\resumoEmpresaPrecosRelativos_df.csv")

Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 31, in <module>
    tabela_df = pd.read_csv(diretorio+"\\"+str(tickerDir)+"\\"+str(files))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Traceback (most recent call last):
  File "C:\Users\harri\AppData\Local\Temp\ipykernel_5068\1880239182.py", line 113, in <module>
    tabela_df[['receita_liquida_valor', 'receita_liquida_unidade']] = tabela_df['receita_liquida'].apply(converter_valor).apply(pd.Series)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\harri\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")

Salvando